/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
val cl = Action<Task> { println("This is as simple folder") }

tasks.register("hello") { doLast(cl) }
