version: '3.1'
services:
  neo4j:
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - '$HOME/neo4j/data:/data'
      - '$HOME/neo4j/logs:/logs'
    image: neo4j

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example


    image: mongo-express
    restart: always
    ports:
mongo-express:      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example