/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

val cl = Action<Task> { println("I'm ${this.project.name}") }

tasks.register("hello") { doLast(cl) }

// Use Kotlin test spec Kotlintest (https://github.com/kotlintest/kotlintest)
val test by tasks.getting(Test::class) {
    useJUnitPlatform { }
}

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    kotlin("jvm") version "1.3.50"
    kotlin("plugin.spring") version "1.3.50"
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.springframework:spring-context:5.1.9.RELEASE")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use junit 5 (https://www.baeldung.com/junit-5-gradle)
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.5.1")
    testRuntimeOnly( "org.junit.jupiter:junit-jupiter-engine:5.5.1")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // Use Kotlin test spec Kotlintest (https://github.com/kotlintest/kotlintest)
    testImplementation("io.kotlintest:kotlintest-runner-junit5:3.3.2")

    testImplementation("io.mockk:mockk:1.9.3")
    testImplementation("io.mockk:mockk-common:1.9.3")

    // slf4j(from kotlintest) -> log4j2 (implementation) -> yaml (configuration)
    testImplementation("org.apache.logging.log4j:log4j-api:2.12.0")
    testImplementation("org.apache.logging.log4j:log4j-core:2.12.0")
    testImplementation("org.apache.logging.log4j:log4j-slf4j-impl:2.12.0")
    testImplementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.9.9")
    testImplementation("com.fasterxml.jackson.core:jackson-databind:2.9.9.1")
}


